# Generated by Django 3.2.5 on 2021-07-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
